x-api-common: &api-common
  container_name: twhp-api-auth
  ports:
    - 8888:8888
  depends_on:
    - database
  networks:
    - twhp-internal
    - twhp-shared
  env_file:
    - docker.env
  volumes:
    - assets:/app/assets
    - ./seed_data:/app/prisma/seed_data:ro
  command: |
    sh -c "
      bun prisma generate
      bun run build
      bun prisma migrate deploy
      bun prisma db seed
      bun run start:prod
    "
  healthcheck:
    test: ["CMD", "curl", "http://localhost:8888/twhp/api/health/api"]
    interval: 10m
    timeout: 5s
    retries: 5
    start_period: 5s

services:
  database:
    image: postgres:17-alpine
    container_name: twhp-db
    restart: always
    env_file:
      - docker.env
    ports:
      - 5660:5432
    volumes:
      - postgres_data-wnwp:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -p 5432 -U $$POSTGRES_USER -d $$POSTGRES_DB",
        ]
      interval: 10m
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - twhp-internal

  api-dev:
    <<: *api-common
    profiles:
      - "dev"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - jaeger
      - fluent-bit
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: api-dev

  api-prod:
    <<: *api-common
    profiles:
      - "production"
    image: rawinan/auth-client:latest
    depends_on:
      - database
      - jaeger
      - fluent-bit
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: api-prod

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: twhp-jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
    env_file:
      - docker.env
    networks:
      - twhp-internal

  prometheus:
    image: prom/prometheus:latest
    container_name: twhp-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - twhp-internal

  grafana:
    image: grafana/grafana:latest
    container_name: twhp-grafana
    env_file:
      - docker.env
    depends_on:
      - prometheus
      - opensearch
    networks:
      - twhp-internal

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: twhp-opensearch
    env_file:
      - docker.env
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - twhp-internal

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: twhp-opensearch-dashboards
    env_file:
      - docker.env
    depends_on:
      - opensearch
    networks:
      - twhp-internal

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: twhp-fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - opensearch
    networks:
      - twhp-internal

  gateway:
    image: nginx:alpine
    container_name: twhp-gateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - grafana
      - opensearch-dashboards
      - jaeger
    networks:
      - twhp-internal

volumes:
  postgres_data-wnwp:
  assets:
  opensearch_data:

networks:
  twhp-shared:
    external: true
  twhp-internal:
    driver: bridge
