services:
  database:
    image: postgres:17-alpine
    container_name: wnwp-db
    restart: always
    env_file:
      - docker.env
    ports:
      - 5660:5432
    volumes:
      - postgres_data-wnwp:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data-wnwp:
